inherit_gem:
  salsify_rubocop: conf/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

Naming/FileName:
  Exclude:
    - 'lib/avro_schema_registry-client.rb'
    - 'spec/avro_schema_registry-client_spec.rb'
